#-----------------------------------
--- # Application
#-----------------------------------

spring:
  application:
    name: APP_NAME
  profiles:
    active:
      - "development"
  main:
    lazy-initialization: false
server:
  port: 8089


--- ## Production

spring:
  config:
    activate:
      on-profile: "production"
  main:
    lazy-initialization: true

#-----------------------------------
--- # i18n & L10n
#-----------------------------------

spring:
  messages:
    encoding: UTF-8
    basename: i18n/messages

#-----------------------------------
--- # Logging
#-----------------------------------

logging:
  level:
    com:
      tujuhsembilan: TRACE

--- ## Production

spring:
  config:
    activate:
      on-profile: "production"
logging:
  level:
    com:
      tujuhsembilan: INFO

#-----------------------------------
--- # Miscellanous
#-----------------------------------

spring:
  output:
    ansi:
      enabled: always

# # -----------------------------------
--- # Database
# # -----------------------------------

spring:
  ## Datasource
  datasource:
    url: jdbc:postgresql://cloudias79.com:5423/db_talentcenter_dev
    username: pgadmin
    password: majubersama
    driver-class-name: org.postgresql.Driver
  ## Configuration
  jpa:
    show-sql: true
    # database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      # COMMENT OUT OR CHANGE TO VALIDATE ON PRODUCTION
      ddl-auto: validate

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

#-----------------------------------
--- # Storage Service (MinIO)
#-----------------------------------

application:
  minio:
    url: https://minio.cloudias79.com/
    username: devtalentcenter
    password: as4Dx6L4Uf1zFkyy

#-----------------------------------
--- # SMTP Settings
#-----------------------------------
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=moodmatchaa@gmail.com
spring.mail.password=caurqpsotxkjtgwc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

